import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Ibarra_Real_Nova } from "next/font/google";
import Navbar from "./ui/Navbar";

// const almendra = Almendra({
//   subsets: ["latin"],
//   variable: "--font-almendra",
//   weight: ["400", "700"],
// })

const ibarraRealNova = Ibarra_Real_Nova({
  subsets: ["latin"],
  variable: "--font-ibarra-real-nova",
  weight: ["400", "700"],
})

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Menu items as an array of Record<string, string>
const menuItems = [
  {name: "Home", path: "/"},
  {name: "Blog", path: "/post"},
  {name: "About", path: "/about"},
  {name: "Contact", path: "/contact"}
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return ( 
    <html lang="en">
      <body
        className={`${ibarraRealNova.variable} ${geistMono.variable} min-h-screen antialiased bg-maize`}
      >
        <Navbar menuItems={menuItems} currentPage={"Home"}/>
        {children}
      </body>
    </html>
  );
}
